title: Keep going..
tagline: Fantasio
description: Thinking by doing
#baseurl: 'http://jwryu87.github.io'
url: 'http://jwryu87.github.io'
logo: /public/fatnasio-logo.png
plugins:
  - jekyll-paginate
  - jekyll-algolia
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: <!-- more -->
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty
ink: pretty
version: 1.0.0
author:
  name: Fantasio
  description: >-
    A passionate <strong>developer and researcher</strong>, learning to be a
    giant.
  contact:
    github: 'https://github.com/jwryu87'
    email: jwryu87@gmail.com
nav:
  Home:
    - /
  PE:
    - /pe/
  Tags:
    - /tags/
  Archive:
    - /archive/
#  Work:
#    - /work/
#    - MyData: /work/mydata/
#    - SODAR: /work/sodar/
#    - Bookmark: /work/bookmark/
  About:
    - /about/
tag_page: /tags/
disqus_short_name: jwryu87-github-io
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# algoria search
#search: true
#search_full_content: true
#search_provider: algolia
#algolia:
#  application_id: 6LIMTKXH6D
#  index_name: dev_fantasio
#  files_to_exclude: []
#  nodes_to_index: 'article'
#  search_only_api_key: ee6a9669001a8b38986ec6f51317acf3

# Analytics
analytics:
  provider               : "google-gtag"
                          # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-VYN0SC3Y6Q"
    anonymize_ip         : # true, false (default)